# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FMDBExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SQLCipher', '3.1.0'
  pod 'FMDB/SQLCipher'   # FMDB with SQLCipher
  #pod 'FMDB' #when use it code will be error

  # Pods for FMDBExample

  target 'FMDBExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FMDBExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
